=== MaurizioCasciano/calciamentis/www.scarpe.it/WebContent/dtd/scarpe.dtd
<!ELEMENT scarpe (scarpa+)>
<!ELEMENT scarpa (idScarpe, marca, modello, prezzo_vendita, prezzo_acquisto, quantitaDisp, scorta_minima, 
				   alt, descrizione, immagini, dettagli)>
<!ELEMENT idScarpe (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modello (#PCDATA)>
<!ELEMENT prezzo_vendita (#PCDATA)>
<!ELEMENT prezzo_acquisto (#PCDATA)>
<!ELEMENT quantitaDisp (#PCDATA)>
<!ELEMENT scorta_minima (#PCDATA)>
<!ELEMENT alt (#PCDATA)>
<!ELEMENT descrizione (#PCDATA)>
<!ELEMENT immagini (url+)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT dettagli (dettaglio+)>
<!ELEMENT dettaglio (intestazione, corpo)>
<!ELEMENT intestazione (#PCDATA)>
<!ELEMENT corpo (#PCDATA)>

=== MaurizioCasciano/calciamentis/www.scarpe.it/WebContent/xml/scarpe.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scarpe SYSTEM "http://127.0.0.1:8080/www.scarpe.it/dtd/scarpe.dtd">
<scarpe>
  <scarpa>
    <idScarpe>29</idScarpe>
    <marca>Nike</marca>
    <modello>ZOOM_ASCENTION</modello>
    <prezzo_vendita>81</prezzo_vendita>
    <prezzo_acquisto>54</prezzo_acquisto>
    <quantitaDisp>148</quantitaDisp>
    <scorta_minima>20</scorta_minima>
    <alt>Nike_ZOOM_ASCENTION</alt>
    <descrizione>blablabla</descrizione>
    <immagine>
      <url>img/Nike_ZOOM_ASCENTION/Nike_ZOOM_ASCENTION0.jpg</url>
      <url>img/Nike_ZOOM_ASCENTION/Nike_ZOOM_ASCENTION1.jpg</url>
      <url>img/Nike_ZOOM_ASCENTION/Nike_ZOOM_ASCENTION2.jpg</url>
      <url>img/Nike_ZOOM_ASCENTION/Nike_ZOOM_ASCENTION3.jpg</url>
      <url>img/Nike_ZOOM_ASCENTION/Nike_ZOOM_ASCENTION4.jpg</url>
    </immagine>
    <dettagli>
      <dettaglio>
        <intestazione>1intest</intestazione>
        <corpo>uyu</corpo>
      </dettaglio>
      <dettaglio>
        <intestazione>Grottolella</intestazione>
        <corpo>huybyu</corpo>
      </dettaglio>
      <dettaglio>
        <intestazione>3intest</intestazione>
        <corpo>hbjvbjkyh</corpo>
      </dettaglio>
      <dettaglio>
        <intestazione>4intest</intestazione>
        <corpo>hjgvhj</corpo>
      </dettaglio>
    </dettagli>
  </scarpa>
</scarpe>
