=== MaurizioCasciano/calciamentis/www.scarpe.it/WebContent/xml/catalog.dtd
<?xml version="1.0" encoding="UTF-8"?>
	<!ELEMENT catalog (shoe+)>
	<!ELEMENT shoe (brand, model, price, image+, alt, description, target, detail*)>
	<!ATTLIST shoe id ID #REQUIRED>
	<!ELEMENT brand (#PCDATA)>
	<!ELEMENT model (#PCDATA)>
	<!ELEMENT price (#PCDATA)>
	<!ELEMENT image (#PCDATA)>
	<!ELEMENT alt (#PCDATA)>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT target (#PCDATA)>
	<!ELEMENT detail (header, paragraph)>
	<!ELEMENT header (#PCDATA)>
	<!ELEMENT paragraph (#PCDATA)>

=== MaurizioCasciano/calciamentis/www.scarpe.it/WebContent/xml/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog SYSTEM "catalog.dtd">
<catalog>
	<shoe id = "a">
		<brand>Nike</brand>
		<model>Mercurial Superfly Leather FG</model>
		<price>302</price>
		<image>img/large/nike/mercurial/superfly/leather/fg/MERCURIAL-SUPERFLY-LTHR-FG-LARGE0.jpg</image>
		<image>img/large/nike/mercurial/superfly/leather/fg/MERCURIAL-SUPERFLY-LTHR-FG-LARGE1.jpg</image>
		<image>img/large/nike/mercurial/superfly/leather/fg/MERCURIAL-SUPERFLY-LTHR-FG-LARGE2.jpg</image>
		<image>img/large/nike/mercurial/superfly/leather/fg/MERCURIAL-SUPERFLY-LTHR-FG-LARGE3.jpg</image>
		<image>img/large/nike/mercurial/superfly/leather/fg/MERCURIAL-SUPERFLY-LTHR-FG-LARGE4.jpg</image>
		<image>img/large/nike/mercurial/superfly/leather/fg/MERCURIAL-SUPERFLY-LTHR-FG-LARGE5.jpg</image>
		<alt>Scarpa da calcio per terreni duri Nike Mercurial Superfly Leather FG - Uomo</alt>
		<description>Scarpa da calcio per terreni duri.</description>
		<target>leatherfg.jsp</target>
		
		<detail>
		<header>PELLE PREMIUM PER MASSIMA VELOCITÀ</header>
		<paragraph>Caratterizzata dall'innovativa fusione di Flyknit e pelle senza cuciture, la scarpa da calcio per terreni duri Nike Mercurial Superfly Leather - Uomo è studiata per offrire agli attaccanti più aggressivi una calzata incredibilmente stabile e morbida e una velocità esplosiva in campo.</paragraph>
		</detail>
		
		<detail>
		<header>CALZATA OTTIMALE</header>
		<paragraph>La tomaia in Flyknit senza cuciture con pelle di canguro ultrasottile, i cavi in Flywire e il collare Dynamic Fit si uniscono per offrire la massima stabilità e una calzata eccezionale.</paragraph>
		</detail>
			
		<detail>
		<header>TOCCO ECCELLENTE</header>
		<paragraph>La pelle testurizzata con tecnologia All Conditions Control (ACC) favorisce la presa sul pallone per un controllo ottimale con piedi bagnati e asciutti.</paragraph>
		</detail>
			
		<detail>
		<header>TRAZIONE ESPLOSIVA</header>
		<paragraph>Il piatto suola in fibra di carbonio, leggero e altamente reattivo, e la struttura di trazione Vapor offrono una velocità esplosiva in campo.</paragraph>
		</detail>
			
		<detail>
		<header>MAGGIORI INFORMAZIONI</header>
		<paragraph>Sottopiede leggero e traforato che segue la forma del piede per il massimo comfort e un'ammortizzazione a basso profilo. Tacchetti per terreni duri (FG) da utilizzare su campi in erba corta leggermente bagnati ma non fangosi.</paragraph>
		</detail>
	</shoe>
	
	<shoe id = "superflyfg">
		<brand>Nike</brand>
		<model>Mercurial Superfly FG</model>
		<price>277</price>
		<image>img/MERCURIAL_SUPERFLY_FG.png</image>
		<alt>Scarpa da calcio MERCURIAL SUPERFLY FG</alt>
		<description>Scarpa da calcio per terreni duri.</description>
		<target>leatherfg.jsp</target>
	</shoe>
	
	<shoe id = "superflyfgid">
		<brand>Nike</brand>
		<model>Mercurial Superfly FG iD</model>
		<price>315</price>
		<image>img/MERCURIAL_SUPERFLY_FG_ID.png</image>
		<alt>Scarpa da calcio MERCURIAL SUPERFLY FG ID</alt>
		<description>Scarpa da calcio per campi in erba naturale.</description>
		<target>leatherfg.jsp</target>
	</shoe>
</catalog>
